let ques=["Binary Search Algorithm – Iterative and Recursive Implementation",
    "Best Time to Buy and Sell Stock",
    "find element twise",
    "reverse element",
    "pair in an array",
    "sum of all subarray",
    "maximun subarray sum(brute forse/prefix/kadane)",
    "Trapping water",
    "rotate array search",
    "smallest element int rotate array",
    "inserttion sort",
    "selection sort",
    "counting sort",
    "merge sort",
    "quick sort",
    "heap sort",
    "spiral matrix/digonal sum",
    "search in rotate array",
    "transpose Matrix",
    "check String palindrome",
    "given a route connecting  4 directions(E,W,N,S) find the sortest path to reach destination'WNEENSNNN'",
    "largest number form an array {'3','30','34','5','9'}",
    "find largest String in the array",
    "the first letter of each word to upper case",
    "String compression('aabccdbdd->a2b2c2d3')",
    "reverse vowel and reverse words in a string",
    "check if a number even or odd using bit manipulation",
    "get ith bit/set ith bit/clear ith bit/update ith bit/clear range of bits in bit manipulation",
    "check if a  number is power of 2 or not",
    "count set bit in a number",
    "Fast exponencial",
    "convert Upercase to Lowercase use manipulation",
    "find array is sorted",
    "fast / last occcurance",
    "fibonacci / natural number",
    "print x to the power n (log n)",
    "tilling problem",
    "remove duplicate int a String",
    "Frinds pairing problem",
    "Binary String problem/Find string length",
    "find count of all contiguous subString starting and ending with same charecter",
    "tower of henoi",
    "mejority Element",
    "pandomize quick sort",
    "Inversion sort",
    "find and print all subset of a given String(ab-> a,b,ab)",
    "print all permutation of string(abc -> abc,acb,bca,bac,cab,cba)",
    "n queens / count total n queens",
    "find number of ways to reach from(0,0) to (n-1,m-1) in  a n x m grid. all moves ->right and down",
    "complete a sudoku",
    "rat a maze(right,left,up,down)",
    "keypad combination -> 23- >ad,ae,af,bd,be,......",
    "knight tour",
    "multi dimantional arrayList",
    "container with most water-> 1,8,6,2,5,4,8,3,7->49",
    "pair sum[list: 1,2,3,4,5,6 target: 5 -> (1,4) (2,3)]",
    "pair sum(sorted and roteted array) list:3,4,5,1,2  target:5",
    "lonely number(10,5,6,8) ans:10,8",
    "Beautifull arrayList[ 5  ans:->1,5,3,2,4]",
    "design linkedlist",
    "reverse linked list 1 & 2",
    "check linked list is palindrome",
    "detect cycle in linked list",
    "remove cycle in linked list",
    "merge sort on linked list",
    "zig zag linked list",
    "reverse double linked list",
    "Implement stack using Arraylist/Linked List",
    "push at the buttom of the stack",
    "reverse at the buttom of the stack and reverse a stack ",
    "stock span problem 100,8060,70,60,85 - > 1,1,1,2,1,6",
    "next greater Element",
    "valid parenthesis / duplicate parenthesis->(((a+b)-c))",
    "max area histogram 2,1,5,6,2,3 -> 6",
    "linked list palindrome using stack",
    "simplify path",
    "trapping rain water using stack",
    "Implement queue using array",
    "Implement circular queue using array",
    "Implement queue using linked list",
    "Implement queue using 2 stack",
    "Implement stack using 2 queue ",
    "first non reapeating charector in a Streem of charector -> aabccxb - a -1 b b b b x",
    "Interleave 2 Halves of a Queue(even length) 1,2,3,4,5,6,7,8,9,10 - > 1,6,2,7,3,8,4,9,5,10",
    "Deque all operation using jcf",
    "Queue reversal",
    "Implement stack and queue using deque",
    "Generate Binary Number n=5 -> 1 10 11 100 101",
    "connect N ropes with minimum cost n = 4  (4,2,3,6)",
    "sliding window maximum",
    "reverse the first k element of a queue",
    "Activity Selection start=[10,12,20],end=[20,25,30]",
    "fractional Knapsack value=[60,100,120],weight=[10,20,30],w = 50",
    "min absolute diff pair a=[1,2,3] b = [2,1,3] ans = 0",
    "maxlength length chain of pairs  pairs=(5,24  39,60 5,28 27,40 50,90)",
    "Indian coins v =121 ans=3",
    "job searching problem",
    "chocola problem or min cost to cut board into square",
    "lexicographically smallest String of length n and sum k n=5,k=42 ans= aaamz",
    "buy and sell stock || ",
    "build binary tree/perform all traversal",
    "hight of nodes/count of nodes/sum of nodes",
    "find buttom left tree value(given the root of binary tree,return the left most value in the last row of the tree)",
    "top view of a tree/buttom view of a tree",
    "right view of a tree/left view of a tree",
    "subtree of another tree",
    "diameter of a tree",
    "kth level of a tree k=2 ",
    "lowest common ancester",
    "minimum distanse between nodes n1 = 4 ,n2 = 6",
    "kth Ancester of a node n =5 k =2",
    "Transform to sumtree",
    "delete leaf node x",
    "Find all duplicate subtree",
    "Minimum path sum in BT",
    "build a bst / search a bst",
    "delete a node in bst / print in range  / print root to leaf",
    "Validate bst",
    "mirror of a bst",
    "Sorted array to balanced bst",
    "size of largest bst in bt",
    "sum of largest bst in bt",
    "Merge 2 bst",
    "Avl trees",
    "heap implementation",
    "Nearest k point to the origin",
    "connect N ropes",
    "weakest soilder",
    "sliding window maximum",
    "Implement hashMap",
    "mejority element /valid anagram",
    "Iterator in Hashmap & hashset/linkedHashMap/treemap",
    "count distinct element / find itenary(journey) from ticket",
    "Largest subarray with sum 0",
    "subarray sum is equal to k",
    "bottom view of a binary tree",
    "sort charector by frequency",
    "insert and search in trie",
    "word break problem",
    "uniue prefix word={'zebre', 'dog','duck','dove'} => 'z','dog','du','dov'",
    "startwith problem word = {apple,app,mango,man} prefix- ap = true , moon = false",
    "count unique substring - ababa = 10",
    "longest word with all prefixes",
    "create graph / bfs / dfs / has path",
    "connected component / cycle detection - directed and undirected",
    " topological sort / top sort using khans algo",
    "bipartite graph / all path from src to dest",
    "dijkstra algo / bellman ford algo",
    "minimum spanning tree(use prims)  and kruskal algo",
    "chipest flight with in k stops ",
    "connecting cities with minimum cost",
    "disjoint set data structure",
    "flood fill algo",
    "strongly connected connected(kosaraju)",
    "bridge in graph(targan)",
    "Articulan point(targen algo)",
    "fibonacci / climbing stair",
    "0-1 knapsack",
    "target sum",
    "unbounded knapsack",
    "coin change",
    "permutation(377 leetcode)",
    "rod cutting",
    "house rober",
    "longest common subsequence",
    "longest incressing subsequence",
    "Edit distance",
    "partition equal to subset sum",
    "longest palindromic subsequence",
    "wildcard matching",
    "catalan number",
    "counting trees",
    "mountain range",
    "matrix chain maultiplication",
    "min array jump",
    "predict the winner",
    "longest bitonic subset"

    
]
// let link=["https://www.geeksforgeeks.org/problems/binary-search-1587115620/1?itm_source=geeksforgeeks&itm_medium=article&itm_campaign=bottom_sticky_on_article","https://leetcode.com/problems/best-time-to-buy-and-sell-stock/description/"]


let btn = document.querySelector("button");
let main = document.querySelector(".main");
let count =0;

btn.addEventListener("click",()=>{
    let ranIdx = Math.floor(Math.random()*177);
    if(count<=2){
        let str = ques[ranIdx];
        let span = document.createElement("h3");
        span.innerText = `Question ${count} :  ${str}` ;
        span.style.color = "green";
        main.append(span);
    }
    count++;
})
